name: Azure Bicep Actions

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Environment
        type: choice
        options: [testing, acceptance, production]
        default: testing

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Az and Bicep versions
        run: |
          az version
          az bicep version

      - name: Lint Bicep
        run: |
          az bicep build --file ./templates/main.bicep

      - name: Validate template at subscription scope
        run: |
          az deployment sub validate \
            --location switzerlandnorth \
            --template-file ./templates/main.bicep

      - name: What if preview
        if: ${{ success() }}
        run: |
          az deployment sub what-if \
            --location switzerlandnorth \
            --template-file ./templates/main.bicep

      - name: Deploy subscription template
        if: ${{ success() }}
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: switzerlandnorth
          template: ./templates/main.bicep
          failOnStdErr: false
